### ISSUE TITLE
似乎有一个bug

### ISSUE THREAD

**Issue by james47** [junrushao/ACM-ICPC-Standard-Code-Library#2]
在`main.tex`的677行：

>  \item 球与盒子的动人故事: ($n$个球, $m$个盒子, $S$为第二类斯特林数) 
>     ...
>     \item 球同, 盒不同, 可空: $\binom{n + m - 1}{**n** - 1}$
>     ...

$m$个盒子，插板插的应该是$m - 1$，所以应为：

>  \item 球与盒子的动人故事: ($n$个球, $m$个盒子, $S$为第二类斯特林数) 
>     ...
>     \item 球同, 盒不同, 可空: $\binom{n + m - 1}{**m** - 1}$
>     ...

**Comment by yzgysjr** [comment]
Thanks a lot for your issue. This is an embarrassing typo :smile:
